### ISSUE TITLE
canot import vector from flet

### ISSUE THREAD

**Issue by bobwatcherx** [flet-dev/examples#107]
i try you sample floating action button menu

but error no found package vector 

Traceback (most recent call last):
  File "C:\Users\LENOVO\Pictures\fletapp\flet2\main.py", line 4, in <module>
    from fab import AnimatedMenuButton, MenuItem
  File "C:\Users\LENOVO\Pictures\fletapp\flet2\fab.py", line 9, in <module>
    from flet import (
ImportError: cannot import name 'Vector' from 'flet' (C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\__init__.py)

**Comment by bobwatcherx** [comment]
from this file 
https://github.com/flet-dev/examples/blob/main/python/community/floating_menu_button/menubutton.py

**Comment by leo-smi** [comment]
up

**Comment by non-npc** [comment]
You can get it working by importing the vector properly. There are other issues with the example however that I do not have time to resolve at the moment (Error displaying ElevatedButton), 

Here is the code to import the vector properly

`import math
import threading
import time
from dataclasses import dataclass, field
from typing import Callable, Optional

import flet
from beartype.typing import List
from flet import (
    ButtonStyle,
    ClipBehavior,
    Container,
    ElevatedButton,
    FilledButton,
    Page,
    Stack,
    colors,
    icons,
)
from flet_core.utils import Vector`
