### ISSUE TITLE
python/tutorials/solitaire/solitaire-final-part1 (WINDOWS 11)

### ISSUE THREAD

**Issue by andresgmg** [flet-dev/examples#97]
Exception in thread Thread-102 (__sync_handler):
Traceback (most recent call last):
  File "...\flet-env\Lib\site-packages\flet_core\event_handler.py", line 28, in __sync_handler
    h(r)
  File "...\solitaire\solitaire-final-part1\card.py", line 126, in drop
    self.update()
  File "...\flet-env\Lib\site-packages\flet_core\control.py", line 260, in update
    assert self.__page, "Control must be added to the page first."
AssertionError: Control must be added to the page first.

NOTE: flet-env is my virtual-environment where I tested.

**Comment by andresgmg** [comment]
python/tutorials/solitaire/solitaire-final-part1 (WINDOWS 11)
